version: '2'
services:
  hexo:
    #command: ["loop"]
    restart: "no"
    build:
        context: hexo
    container_name: hexo
    ports:
      - "4000:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - $HOME/.ssh:/root/.ssh
     - $PWD/source:/hexo/source
     - $PWD/themes:/hexo/themes
     - $PWD/_config.yml:/hexo/_config.yml
    environment:
     - "GIT_USER_NAME=${GIT_USER_NAME}"
     - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
     - "BEFORE_HEXO=${BEFORE_HEXO}"
